# Generated by Django 4.1 on 2022-08-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.TextField(default='yellow', max_length=100, verbose_name='Цвет папки'),
        ),
    ]
