# Generated by Django 4.1 on 2022-08-30 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_alter_color_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='color',
            field=models.ForeignKey(blank=True, default='yellow', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.color', verbose_name='Цвет папки'),
        ),
    ]
