# Generated by Django 4.1 on 2022-11-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_alter_file_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='messages',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Ccылки на чанки в ТГ'),
        ),
    ]
